# Setup
title:            Japón 2014
repository:       alvarovmz/japan
tagline:          'El viaje'
description:      'Una historia épica de acción y aventuras en el lejano oriente'
paginate: 30
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Alvaro'
  url:            https://twitter.com/alvarovmz

plugins:
  - jekyll-paginate

github:
  repo:           https://github.com/alvarovmz/japan
