# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Japón 2014
tagline:          'El viaje'
description:      'Una historia épica de acción y aventuras en el lejano oriente'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         30

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
